RDO版packstackではEPELを有効にしないとpython-novaのインストールで失敗する問題があったので手順に追記
ERROR : Error appeared during Puppet run: 172.17.14.126_api_nova.pp
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install python-nova'
returned 1: Error: Package: python-nova-2015.1.1-1.el7.noarch
(openstack-kilo)
[root@opst-ctl ~]# yum install python-nova
--> Finished Dependency Resolution
Error: Package: python-nova-2015.1.1-1.el7.noarch (openstack-kilo)
           Requires: python-cheetah
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest